// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notifications/v1/notifications.proto

package notificationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Vars          map[string]string      `protobuf:"bytes,4,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SendRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendRequest) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *SendRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *SendResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesRequest) Reset() {
	*x = ListDeliveriesRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesRequest) ProtoMessage() {}

func (x *ListDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *ListDeliveriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeliveriesRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type DeliveryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DevPayload    string                 `protobuf:"bytes,7,opt,name=dev_payload,json=devPayload,proto3" json:"dev_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryRecord) Reset() {
	*x = DeliveryRecord{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRecord) ProtoMessage() {}

func (x *DeliveryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRecord.ProtoReflect.Descriptor instead.
func (*DeliveryRecord) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryRecord) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *DeliveryRecord) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *DeliveryRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeliveryRecord) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *DeliveryRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DeliveryRecord) GetDevPayload() string {
	if x != nil {
		return x.DevPayload
	}
	return ""
}

type ListDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*DeliveryRecord      `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesResponse) Reset() {
	*x = ListDeliveriesResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesResponse) ProtoMessage() {}

func (x *ListDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *ListDeliveriesResponse) GetDeliveries() []*DeliveryRecord {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

var File_notifications_v1_notifications_proto protoreflect.FileDescriptor

const file_notifications_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"$notifications/v1/notifications.proto\x12\x10notifications.v1\"\xfe\x01\n" +
	"\vSendRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12;\n" +
	"\x04vars\x18\x04 \x03(\v2'.notifications.v1.SendRequest.VarsEntryR\x04vars\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\fSendResponse\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"G\n" +
	"\x15ListDeliveriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"\xd5\x01\n" +
	"\x0eDeliveryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vdev_payload\x18\a \x01(\tR\n" +
	"devPayload\"Z\n" +
	"\x16ListDeliveriesResponse\x12@\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2 .notifications.v1.DeliveryRecordR\n" +
	"deliveries2\xc2\x01\n" +
	"\x14NotificationsService\x12E\n" +
	"\x04Send\x12\x1d.notifications.v1.SendRequest\x1a\x1e.notifications.v1.SendResponse\x12c\n" +
	"\x0eListDeliveries\x12'.notifications.v1.ListDeliveriesRequest\x1a(.notifications.v1.ListDeliveriesResponseBQZOgithub.com/manovaspace/orbit-notifications/api/notifications/v1;notificationsv1b\x06proto3"

var (
	file_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_notifications_v1_notifications_proto_rawDescData []byte
)

func file_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_v1_notifications_proto_rawDesc), len(file_notifications_v1_notifications_proto_rawDesc)))
	})
	return file_notifications_v1_notifications_proto_rawDescData
}

var file_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notifications_v1_notifications_proto_goTypes = []any{
	(*SendRequest)(nil),            // 0: notifications.v1.SendRequest
	(*SendResponse)(nil),           // 1: notifications.v1.SendResponse
	(*ListDeliveriesRequest)(nil),  // 2: notifications.v1.ListDeliveriesRequest
	(*DeliveryRecord)(nil),         // 3: notifications.v1.DeliveryRecord
	(*ListDeliveriesResponse)(nil), // 4: notifications.v1.ListDeliveriesResponse
	nil,                            // 5: notifications.v1.SendRequest.VarsEntry
}
var file_notifications_v1_notifications_proto_depIdxs = []int32{
	5, // 0: notifications.v1.SendRequest.vars:type_name -> notifications.v1.SendRequest.VarsEntry
	3, // 1: notifications.v1.ListDeliveriesResponse.deliveries:type_name -> notifications.v1.DeliveryRecord
	0, // 2: notifications.v1.NotificationsService.Send:input_type -> notifications.v1.SendRequest
	2, // 3: notifications.v1.NotificationsService.ListDeliveries:input_type -> notifications.v1.ListDeliveriesRequest
	1, // 4: notifications.v1.NotificationsService.Send:output_type -> notifications.v1.SendResponse
	4, // 5: notifications.v1.NotificationsService.ListDeliveries:output_type -> notifications.v1.ListDeliveriesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notifications_v1_notifications_proto_init() }
func file_notifications_v1_notifications_proto_init() {
	if File_notifications_v1_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_v1_notifications_proto_rawDesc), len(file_notifications_v1_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_v1_notifications_proto_depIdxs,
		MessageInfos:      file_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_notifications_v1_notifications_proto = out.File
	file_notifications_v1_notifications_proto_goTypes = nil
	file_notifications_v1_notifications_proto_depIdxs = nil
}
